name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
        with:
          path: ${{ github.event.repository.name }}
            
      - name: Checkout `worlds`
        uses: actions/checkout@v4.1.2
        with:
          repository: game-simulations/worlds
          token: ${{ secrets.PAT }}
          path: worlds
      
      - name: Checkout `types`
        uses: actions/checkout@v4.1.2
        with:
          repository: game-simulations/types
          token: ${{ secrets.PAT }}
          path: types
      
      - name: Checkout `data`
        uses: actions/checkout@v4.1.2
        with:
          repository: game-simulations/data
          token: ${{ secrets.PAT }}
          path: data
      
      - name: Checkout `unmanaged`
        uses: actions/checkout@v4.1.2
        with:
          repository: game-simulations/unmanaged
          token: ${{ secrets.PAT }}
          path: unmanaged
      
      - name: Checkout `textures`
        uses: actions/checkout@v4.1.2
        with:
          repository: game-simulations/textures
          token: ${{ secrets.PAT }}
          path: textures
      
      - name: Checkout `rendering`
        uses: actions/checkout@v4.1.2
        with:
          repository: game-simulations/rendering
          token: ${{ secrets.PAT }}
          path: rendering
      
      - name: Checkout `cameras`
        uses: actions/checkout@v4.1.2
        with:
          repository: game-simulations/cameras
          token: ${{ secrets.PAT }}
          path: cameras
      
      - name: Checkout `transforms`
        uses: actions/checkout@v4.1.2
        with:
          repository: game-simulations/transforms
          token: ${{ secrets.PAT }}
          path: transforms
      
      - name: Checkout `transform-systems`
        uses: actions/checkout@v4.1.2
        with:
          repository: game-simulations/transform-systems
          token: ${{ secrets.PAT }}
          path: transform-systems
      
      - name: Checkout `simulation`
        uses: actions/checkout@v4.1.2
        with:
          repository: game-simulations/simulation
          token: ${{ secrets.PAT }}
          path: simulation
      
      - name: Checkout `collections`
        uses: actions/checkout@v4.1.2
        with:
          repository: game-simulations/collections
          token: ${{ secrets.PAT }}
          path: collections
      
      - name: Checkout `shaders`
        uses: actions/checkout@v4.1.2
        with:
          repository: game-simulations/shaders
          token: ${{ secrets.PAT }}
          path: shaders
      
      - name: Checkout `meshes`
        uses: actions/checkout@v4.1.2
        with:
          repository: game-simulations/meshes
          token: ${{ secrets.PAT }}
          path: meshes
      
      - name: Checkout `materials`
        uses: actions/checkout@v4.1.2
        with:
          repository: game-simulations/materials
          token: ${{ secrets.PAT }}
          path: materials
      
      - name: Checkout `bin-packer`
        uses: actions/checkout@v4.1.2
        with:
          repository: game-simulations/bin-packer
          token: ${{ secrets.PAT }}
          path: bin-packer
            
      - name: Setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
            
      - name: Build `Skyboxes`
        run: dotnet build "${{ github.event.repository.name }}/source" -c Release /p:Version=${VERSION}
      
      - name: Build `Skyboxes.Tests`
        run: dotnet build "${{ github.event.repository.name }}/tests" -c Release /p:Version=${VERSION}
            
      - name: Test
        run: dotnet test "${{ github.event.repository.name }}/tests" -c Release --logger "trx"
            
      - name: Pack `Skyboxes`
        run: dotnet pack "${{ github.event.repository.name }}/source" -c Release /p:Version=${VERSION} --no-build --output .

      - name: Add NuGet Source
        run: dotnet nuget add source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --name github --username ${{ github.repository_owner }} --password ${{ github.token }} --store-password-in-clear-text
            
      - name: Publish `Skyboxes`
        run: dotnet nuget push Skyboxes.${VERSION}.nupkg --source github --api-key ${NUGET_TOKEN}
        env:
          NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}