name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
        with:
          path: ${{ github.event.repository.name }}
            
      - name: Checkout `cameras`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/cameras
          token: ${{ secrets.PAT }}
          path: cameras
      
      - name: Checkout `data`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/data
          token: ${{ secrets.PAT }}
          path: data
      
      - name: Checkout `rendering`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/rendering
          token: ${{ secrets.PAT }}
          path: rendering
      
      - name: Checkout `textures`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/textures
          token: ${{ secrets.PAT }}
          path: textures
      
      - name: Checkout `worlds`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/worlds
          token: ${{ secrets.PAT }}
          path: worlds
      
      - name: Checkout `unmanaged`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/unmanaged
          token: ${{ secrets.PAT }}
          path: unmanaged
      
      - name: Checkout `types`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/types
          token: ${{ secrets.PAT }}
          path: types
      
      - name: Checkout `collections`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/collections
          token: ${{ secrets.PAT }}
          path: collections
      
      - name: Checkout `bin-packer`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/bin-packer
          token: ${{ secrets.PAT }}
          path: bin-packer
      
      - name: Checkout `materials`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/materials
          token: ${{ secrets.PAT }}
          path: materials
      
      - name: Checkout `meshes`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/meshes
          token: ${{ secrets.PAT }}
          path: meshes
      
      - name: Checkout `shaders`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/shaders
          token: ${{ secrets.PAT }}
          path: shaders
      
      - name: Checkout `transforms`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/transforms
          token: ${{ secrets.PAT }}
          path: transforms
      
      - name: Checkout `simulation`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/simulation
          token: ${{ secrets.PAT }}
          path: simulation
      
      - name: Checkout `transform-systems`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/transform-systems
          token: ${{ secrets.PAT }}
          path: transform-systems
            
      - name: Setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
            
      - name: Build `Skyboxes`
        run: dotnet build "${{ github.event.repository.name }}/source" -c Debug /p:Version=${VERSION}
      
      - name: Build `Skyboxes`
        run: dotnet build "${{ github.event.repository.name }}/source" -c Release /p:Version=${VERSION}
      
      - name: Build `Skyboxes.Tests`
        run: dotnet build "${{ github.event.repository.name }}/tests" -c Debug /p:Version=${VERSION}
      
      - name: Build `Skyboxes.Tests`
        run: dotnet build "${{ github.event.repository.name }}/tests" -c Release /p:Version=${VERSION}
            
      - name: Test
        run: dotnet test "${{ github.event.repository.name }}/tests" -c Release --logger "trx"
            
      - name: Pack `Skyboxes`
        run: dotnet pack "${{ github.event.repository.name }}/source" /p:Version=${VERSION} --no-build --output .

      - name: Add GitHub source
        run: dotnet nuget add source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --name github --username ${{ github.repository_owner }} --password ${{ github.token }} --store-password-in-clear-text
            
      - name: Publish `Skyboxes` to GitHub registry
        run: dotnet nuget push SimulationTree.Skyboxes.${VERSION}.nupkg --source github --api-key ${API_KEY}
        env:
          API_KEY: ${{ secrets.NUGET_TOKEN_GITHUB }}
      
      - name: Publish `Skyboxes` to official registry
        run: dotnet nuget push SimulationTree.Skyboxes.${VERSION}.nupkg --source nuget.org --api-key ${API_KEY}
        env:
          API_KEY: ${{ secrets.NUGET_TOKEN_OFFICIAL }}